/**
 * runwrap.ts — terminal launch wrappers for compiled programs.
 *
 * v1.5.1 UX fix: a PLAIN console program (no graphics.h) prints its output
 * and exits within milliseconds. Launched directly as the terminal's root
 * process, the terminal closed instantly, so students never saw the output
 * ("normal programs are not running"). The wrapper keeps the window open
 * until a key is pressed. Graphics (BGI) programs keep the direct launch —
 * the BGI window itself is the visible output.
 *
 * Windows uses a generated .cmd launcher next to the exe (immune to the
 * cmd.exe quoting minefield: the shell args are ONE plain path) executed by
 * the absolute ComSpec path; POSIX uses /bin/bash -c with a quoted path.
 *
 * Pure module (fs side effect only in writePauseWrapper): unit-testable.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

export interface TerminalLaunch {
  shellPath: string;
  shellArgs: string[];
  /** the generated wrapper file, when one was written */
  wrapperFile?: string;
  /** true when the wrapper could not be written and the caller should
   * fall back to a direct launch */
  fallback?: boolean;
}

/** POSIX sh quoting (single-quote style, safe for arbitrary paths). */
export function shQuote(s: string): string {
  return "'" + String(s).replace(/'/g, "'\\''") + "'";
}

/** The .cmd script that runs the exe and keeps the window open. */
export function buildPauseCmdScript(exePath: string): string {
  return [
    '@echo off',
    'rem generated by graphics.h Runner - keeps this window open after the program exits',
    '"' + exePath + '"',
    'set GHR_EXITCODE=%ERRORLEVEL%',
    'echo.',
    'echo [program finished with exit code %GHR_EXITCODE%]',
    'echo Press any key to close this window . . .',
    'pause >nul',
    ''
  ].join('\r\n');
}

/** Windows launch: cmd.exe (absolute ComSpec) /c <exe>.run.cmd */
export function writePauseWrapper(exePath: string): TerminalLaunch {
  const comspec =
    process.env.ComSpec ||
    path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'cmd.exe');
  const wrapper = exePath.replace(/\.exe$/i, '') + '.run.cmd';
  try {
    fs.writeFileSync(wrapper, buildPauseCmdScript(exePath), 'utf8');
    return { shellPath: comspec, shellArgs: ['/d', '/c', wrapper], wrapperFile: wrapper };
  } catch {
    /* unwritable folder (rare) — direct launch still shows graphics output */
    return { shellPath: exePath, shellArgs: [], fallback: true };
  }
}

/** POSIX launch: /bin/bash -c '<exe>; print exit code; read' */
export function buildPosixPauseLaunch(exePath: string): TerminalLaunch {
  const script =
    shQuote(exePath) +
    '; s=$?; echo; echo "[program finished with exit code $s]"; ' +
    'read -r -p "Press Enter to close..." _';
  return { shellPath: '/bin/bash', shellArgs: ['-c', script] };
}

/** The exact global compile command shown to students (all platforms). */
export function universalCommandDoc(): string {
  return 'g++ program.cpp -o program.exe -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32';
}

/** The readme dropped into the toolchain root by the global setup step. */
export function buildAnywhereReadme(binDir: string): string {
  return [
    'graphics.h Runner - GLOBAL setup (works without the extension)',
    '==============================================================',
    '',
    'This toolchain folder now contains WinBGIM in its own include/lib',
    'folders, and its bin folder was added to your user PATH:',
    '  ' + binDir,
    '',
    'Compile & run a graphics.h program from ANY terminal (cmd.exe,',
    'PowerShell, Dev-C++, Code::Blocks, CLion, ...):',
    '',
    '  ' + universalCommandDoc().replace('.exe', os.platform() === 'win32' ? '.exe' : ''),
    '',
    'On Linux/macOS the equivalent one-liner is:',
    '  g++ program.cpp -o program -lSDL_bgi -lSDL2 -lm',
    '',
    'To REMOVE the global setup, delete graphics.h / winbgim.h from',
    'include\\ and libbgi.a from lib\\ and remove the bin folder from',
    'your user PATH environment variable.',
    ''
  ].join('\r\n');
}
